# environment.yml
name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - django=5.2.9
  - djangorestframework=3.16.1
  - gdal
  - pip
  - pip:
      - psycopg2-binary==2.9.11
      - drf-spectacular==0.29.0
      - django-cors-headers==4.9.0
      - django-filter==25.2
      - django-environ==0.12.0
      - djangorestframework-camel-case==1.4.2
      - djangorestframework-simplejwt==5.5.1
      - gunicorn==21.2.0
      - PyJWT==2.10.1
      - PyYAML==6.0.3